SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";
--
-- Database: `marketplace`
-- --------------------------------------------------------
-- Table structure for table `cartas`
--

CREATE TABLE `cartas` (
  `id` int NOT NULL,
  `nome` varchar(255) NOT NULL,
  `descricao` text,
  `imagemUrl` varchar(255) DEFAULT NULL,
  `preco` varchar(50) DEFAULT NULL,
  `tipo` varchar(50) DEFAULT NULL,
  `ataque` varchar(50) DEFAULT NULL,
  `defesa` varchar(50) DEFAULT NULL,
  `atributo` varchar(50) DEFAULT NULL,
  `level` varchar(50) DEFAULT NULL,
  `imgExtra1` varchar(255) DEFAULT NULL,
  `imgExtra2` varchar(255) DEFAULT NULL,
  `imgExtra3` varchar(255) DEFAULT NULL,
  `imgExtra4` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--
-- Dumping data for table `cartas`
--
INSERT INTO `cartas` (`id`, `nome`, `descricao`, `imagemUrl`, `preco`, `tipo`, `ataque`, `defesa`, `atributo`, `level`, `imgExtra1`, `imgExtra2`, `imgExtra3`, `imgExtra4`) VALUES
(1, 'dragao branco de olhos azuis', 'Este dragão lendário é uma poderosa máquina de destruição. Praticamente invencível, muito poucos enfrentaram esta magnífica criatura e viveram para contar a história.', 'https://img.mypcards.com/img/3/316/yugioh_ct13-en008/yugioh_ct13-en008_pt.jpg', 'R$10,00', 'Monstro ', '3000', '2500', 'Dragon', '8', 'https://img.mypcards.com/img/3/579/yugioh_ldk2-enk01c/yugioh_ldk2-enk01c_en-1684264311.jpeg', 'https://img.mypcards.com/img/3/579/yugioh_ldk2-enk01b/yugioh_ldk2-enk01b_en-1684264195.jpeg', 'https://img.mypcards.com/img/3/940/yugioh_mvp1-en055/yugioh_mvp1-en055_pt.jpg', 'https://img.mypcards.com/img/3/303/yugioh_bpt-009/yugioh_bpt-009_en.jpg'),
(2, 'Mago Negro', 'O mago definitivo em termos de ataque e defesa', 'https://img.mypcards.com/img/3/1349/yugioh_mago-en002/yugioh_mago-en002_pt.jpg', 'R$20,00', 'Mago', '2500', '2100', 'Spellcaster,Normal', '7', 'https://img.mypcards.com/img/3/1873/yugioh_sbc1_eng01/yugioh_sbc1_eng01_en.jpg', 'https://img.mypcards.com/img/3/1790/yugioh_lc01-25-en005/yugioh_lc01-25-en005_en.jpg', 'https://img.mypcards.com/img/3/2183/yugioh_ra03_en080/yugioh_ra03_en080_en.jpg', 'https://img.mypcards.com/img/3/1256/yugioh_mvp1-ensv3/yugioh_mvp1-ensv3_en.png'),
(5, 'pequena maga negra', 'Este card ganha 300 de ATK para cada Mago Negro ou Mago do Caos das Trevas no Cemitério de qualquer duelista', 'https://img.mypcards.com/img/3/425/yugioh_dl18-en003/yugioh_dl18-en003_pt.jpg', 'R$30,00', 'Mago', '2000', '1700', 'Spellcaster,Effect', '6', 'https://img.mypcards.com/img/3/2164/yugioh_mp24-en053/yugioh_mp24-en053_en-1729173866.jpg', 'https://img.mypcards.com/img/3/1725/yugioh_mp22_en268/yugioh_mp22_en268_en.jpg', 'https://img.mypcards.com/img/3/1710/yugioh_lds3_en082/yugioh_lds3_en082_en.jpg', 'https://img.mypcards.com/img/3/1222/yugioh_lart-en035/yugioh_lart-en035_en.png'),
(6, 'Kuriboh', 'Durante o turno do seu oponente, no cálculo de dano: você pode descartar este card; você não sofre dano de batalha dessa batalha (este é um Efeito Rápido).', 'https://img.mypcards.com/img/3/792/yugioh_sdym_026/yugioh_sdym_026_en.jpg', 'R$30,00', 'Monstro', '300', '200', 'Fiend, Dark, Effect', '1', '', '', '', ''),
(8, 'Obelisco, o Atormentador', 'A vinda desta criatura poderosa será anunciada por ventos ardentes e pelo tremor da terra. E com a chegada deste horror, aqueles que ainda respiram conhecerão o verdadeiro significado do sono eterno.', 'https://img.mypcards.com/img/3/570/yugioh_lc01-en001/yugioh_lc01-en001_en.jpg', 'R$50,00', 'Monstro ', '4000', '4000', 'Divine-Beast', '7', '', '', '', ''),
(9, 'Slifer, o Dragão Celeste', 'Requer 3 Tributos para ser Invocado por Invocação-Normal (não pode ser Baixado Normalmente). A Invocação-Normal deste card não pode ser negada. Quando Invocado por Invocação-Normal, cards e efeitos não podem ser ativados. Uma vez por turno, durante a Fase Final, se este card foi Invocado por Invocação-Especial: envie-o para o Cemitério. Ganha 1000 de ATK/DEF para cada card na sua mão. Se um ou mais monstros forem Invocados por Invocação-Normal ou Especial no campo do seu oponente em Posição de Ataque: esses monstros perdem 2000 de ATK e, depois, se algum deles tiver o ATK reduzido a 0 como resultado, destrua-o.', 'https://img.mypcards.com/img/3/1556/yugioh_kico_en063/yugioh_kico_en063_en.jpg', '498', 'Monstro', '?', '?', 'Divine-Beast,Effect', '10', '', '', '', ''),
(10, 'O Dragão Alado de Rá', 'Não pode ser Invocado por Invocação-Especial. Requer 3 Tributos para ser Invocado por Invocação-Normal (não pode ser Baixado Normalmente). A Invocação-Normal deste card não pode ser negada. Quando Invocado por Invocação-Normal, outros cards e efeitos não podem ser ativados. Quando este card for Invocado por Invocação-Normal: você pode pagar PV até restarem apenas 100; este card ganha ATK/DEF igual aos PV pagos. Você pode pagar 1000 PV e, depois, escolha 1 monstro no campo; destrua o alvo.', 'https://img.mypcards.com/img/3/579/yugioh_ldk2-ens03/yugioh_ldk2-ens03_en-1682610509.jpeg', 'R$50,00', 'Monstro ', '?', '?', 'Divine-Beast,Effect', '10', '', '', '', ''),
(11, 'O Dragão Alado de Rá', 'Não pode ser Invocado por Invocação-Especial. Requer 3 Tributos para ser Invocado por Invocação-Normal (não pode ser Baixado Normalmente). A Invocação-Normal deste card não pode ser negada. Quando Invocado por Invocação-Normal, outros cards e efeitos não podem ser ativados. Quando este card for Invocado por Invocação-Normal: você pode pagar PV até restarem apenas 100; este card ganha ATK/DEF igual aos PV pagos. Você pode pagar 1000 PV e, depois, escolha 1 monstro no campo; destrua o alvo.', 'https://img.mypcards.com/img/3/579/yugioh_ldk2-ens03/yugioh_ldk2-ens03_en-1682610509.jpeg', 'R$50,00', 'Monstro ', '?', '?', 'Divine-Beast,Effect', '10', '', '', '', ''),
(12, 'Bruxa da Floresta Negra', 'Quando este card é enviado do Campo para o Cemitério, escolha 1 Card de Monstro com um DEF de 1500 pontos ou menos do seu Deck, revele-o ao seu adversário e adicione-o à sua mão. Em seguida, embaralhe o seu Deck.', 'https://img.mypcards.com/img/3/762/yugioh_ske-020/yugioh_ske-020_en.png', 'R$5,00', 'Monstro ', '1100', '1200', 'Spellcaster,Dark,Effect ', '4', '', '', '', ''),
(13, 'Riseheart Kashtira', 'Se você controlar um monstro Kashtira: você pode Invocar este card por Invocação-Especial da sua mão e, além disso, você não pode Invocar monstros por Invocação-Especial do Deck Adicional pelo resto deste turno, exceto Monstros Xyz. Durante sua Fase Principal, se este card foi Invocado por Invocação-Normal ou Especial neste turno: você pode banir 1 card Kashtira do seu Deck, exceto Riseheart Kashtira; bana os 3 cards do topo do Deck do seu oponente com a face para baixo e, se você banir algum, o Nível deste card se torna 7. Você só pode usar cada efeito de Riseheart Kashtira uma vez por turno.', 'https://img.mypcards.com/img/3/2164/yugioh_mp24_en065/yugioh_mp24_en065_en.jpg', 'R$55,00', 'Monstro ', '1500', '2100', 'Effect,Warrior', '4', '', '', '', ''),
(14, 'Pote da Ganância', 'Compre 2 cards.', 'https://img.mypcards.com/img/3/576/yugioh_lcjw-en061/yugioh_lcjw-en061_en.jpg', 'R$50,00', 'Magia', '0', '0', 'Normal', '0', '', '', '', ''),
(15, 'Azul Spright', 'Se você controlar um monstro de Nível/Classe 2, você pode Invocar este card por Invocação-Especial (da sua mão). Você só pode Invocar Azul Spright por Invocação-Especial uma vez por turno desta forma. Se este card for Invocado por Invocação-Especial: você pode adicionar 1 monstro Spright do seu Deck à sua mão, exceto Azul Spright. Você só pode usar este efeito de Azul Spright uma vez por turno.', 'https://img.mypcards.com/img/3/2139/yugioh_bltr_en075/yugioh_bltr_en075_en.jpg', 'R$20,00', 'Monstro ', '1100', '1000', 'Effect,Moster', '2', '', '', '', ''),
(16, 'Brionac, o Dragão de Gelo Mágico', '1 Regulador + 1+ monstros não-Reguladores Se este card for Invocado por Invocação-Sincro: você pode descartar 1 card e, depois, escolha 1 card no campo; devolva-o para a mão. Se este card for Invocado por Invocação-Especial do Cemitério: você pode descartar 1 card e, depois, escolha 1 card no campo; devolva-o para a mão. Você só pode usar cada efeito de Brionac, o Dragão de Gelo Mágico uma vez por turno.', 'https://img.mypcards.com/img/3/2139/yugioh_bltr_en004/yugioh_bltr_en004_en.jpg', 'R$8,00', 'Monstro ', '2300', '1400', 'Synchro, Effect, Monster ', '6', '', '', '', ''),
(17, 'Ogro Fantasma & Coelho da Neve', 'Quando um monstro no campo ativar seu efeito, ou quando uma Magia/Armadilha que já esteja com a face para cima no campo ativar seu efeito (Efeito Rápido): você pode enviar este card da sua mão ou do campo para o Cemitério; destrua esse card no campo. Você só pode usar este efeito de \"Ogro Fantasma & Coelho da Neve\" uma vez por turno.\r\n', 'https://img.mypcards.com/img/3/2128/yugioh_ra02_en009/yugioh_ra02_en009_en.jpg', 'R$50', 'Monstro ', '0', '1800', 'Psychic,Tuner,Effect', '3', '', '', '', ''),
(18, 'Dinolutador Pancratops', 'Se seu oponente controlar mais monstros que você, você pode Invocar este card por Invocação-Especial (da sua mão). Você só pode Invocar Dinolutador Pancratops por Invocação-Especial uma vez por turno desta forma. (Efeito Rápido): você pode oferecer 1 monstro Dinolutador como Tributo e, depois, escolha 1 card que seu oponente controla; destrua-o. Você só pode usar este efeito de Dinolutador Pancratops uma vez por turno.', 'https://img.mypcards.com/img/3/2164/yugioh_mp24_en047/yugioh_mp24_en047_en.jpg', 'R$30,00', 'Monstro ', '2600', '0', 'Dinosaur,Effect', '7', '', '', '', ''),
(19, 'Lacrima, as Lágrimas Carmesim', '(Este card deve ser sempre considerado como um card Criademônio.) Se este card for Invocado por Invocação-Normal ou Especial: você pode enviar 1 card Criademônio do seu Deck para o Cemitério, exceto Lacrima, as Lágrimas Carmesim. Durante o turno do seu oponente, se este card estiver no seu Cemitério (Efeito Rápido): você pode escolher 1 Monstro Link Criademônio no seu Cemitério; embaralhe este card no Deck e, se isso acontecer, Invoque esse monstro por Invocação-Especial. Você só pode usar cada efeito de Lacrima, as Lágrimas Carmesim uma vez por turno.', 'https://img.mypcards.com/img/3/2172/yugioh_rota_en014/yugioh_rota_en014_en.jpg', 'R$500,00', 'Monstro ', '1200', '1200', 'Fiend,Effect', '4', '', '', '', ''),
(20, 'Azamina Moa Regina', '1 monstro Ilusão + 1 monstro Demônio de Nível 6 ou mais Você pode escolher 1 monstro Ilusão no seu Cemitério, exceto Azamina Moa Regina; Invoque-o por Invocação-Especial. Quando um card ou efeito Azamina ou Despojos do Pecado for ativado, exceto Azamina Moa Regina (Efeito Rápido): você pode escolher até 2 cards no campo; destrua-os. Você só pode usar cada efeito de Azamina Moa Regina uma vez por turno.', 'https://img.mypcards.com/img/3/2172/yugioh_rota_en033/yugioh_rota_en033_en.jpg', 'R$50,00', 'Monstro ', '3000', '2000', 'Illusion,Fusion,Effect', '8', '', '', '', ''),
(21, 'Azamina Mu Rcielago', '1 monstro Ilusão + 1 monstro Mago de LUZ Monstros que seu oponente controla perdem 500 de ATK/DEF para cada monstro Azamina que você controla. Você só pode usar cada um dos seguintes efeitos de Azamina Mu Rcielago uma vez por turno. Se este card for Invocado por Invocação-Fusão: você pode adicionar 1 card Azamina ou Despojos do Pecado do seu Deck à sua mão. Se este card for destruído em batalha ou por um efeito de card: você pode adicionar 1 Magia Despojos do Pecado do seu Deck à sua mão.', 'https://img.mypcards.com/img/3/2172/yugioh_rota_en031/yugioh_rota_en031_en.jpg', 'R$50,00', 'Monstro ', '2000', '2400', 'Illusion,Fusion,Effect', '6', '', '', '', ''),
(22, 'Guardião Quimera', '3 monstros com nomes diferentes Primeiro deve ser Invocado por Invocação-Fusão usando apenas Matérias de Fusão da sua mão e do campo, com pelo menos 1 monstro de cada. Se este card for Invocado por Invocação-Fusão por um Card de Magia ou seus efeitos: você pode comprar cards igual ao número de cards usados como matéria da mão e, se isso acontecer, destrua cards que seu oponente controla igual ao número de cards usados como matéria do campo. Você só pode usar este efeito de Guardião Quimera uma vez por turno. Enquanto Polimerização estiver no seu Cemitério, seu oponente não pode escolher este card como alvo de efeitos de card.', 'https://img.mypcards.com/img/3/2128/yugioh_ra02_en023/yugioh_ra02_en023_en.jpg', 'R$20,00', 'Monstro ', '3300', '3300', 'Beast,Fusion,Effect', '9', '', '', '', ''),
(23, 'Metal das Trevas, o Dragão do Aço Negro', '2+ Monstros de Efeito com o mesmo Tipo e Atributo Você pode escolher 1 dos seus monstros que estiverem banidos ou no seu Cemitério Invoque-o por Invocação-Especial em uma zona sua para a qual este card apontar, em Posição de Defesa, mas seus efeitos são negados e, além disso, você não pode Invocar Monstros Link por Invocação-Especial pelo resto deste turno e o monstro Invocado é colocado no fundo do Deck quando ele deixar o campo. Você só pode usar este efeito de Metal das Trevas, o Dragão do Aço Negro uma vez por turno.', 'https://img.mypcards.com/img/3/2039/yugioh_blc1_en044/yugioh_blc1_en044_en.jpg', '30', 'Monstro ', '2800', 'Link-4', 'Dragon,Link,Effect', '0', '', '', '', ''),
(24, 'O Imparável Exodia Encarnado', '5 monstros O Proibido Não pode ser destruído por efeitos de card do oponente. Uma vez por turno, se este card batalhar, durante o cálculo de dano você pode fazer com que este card ganhe ATK igual aos seus PV. Uma vez por turno, quando um Card de Magia,Armadilha ou seus efeitos forem ativados Efeito Rápido: você pode negar essa ativação. Uma vez por turno, durante a Fase Final você pode Baixar 1 Magia,Armadilha Exodd ou Obliterar do seu Deck. Uma vez por turno, durante sua Fase de Apoio: perca 1000 PV.', 'https://img.mypcards.com/img/3/2147/yugioh_info_en033/yugioh_info_en033_en.jpg', 'R$35,00', 'Monstro ', '?', '0', 'Spellcaster,Fusion,Effect', '10', '', '', '', ''),
(26, 'O Bistial Lubellion', 'Não pode ser Invocado por Invocação-Normal/Baixado. Deve ser Invocado por Invocação-Especial (da sua mão ou do Cemitério) ao oferecer como Tributo 1 monstro Dragão de TREVAS de Nível 6 ou mais. Você só pode Invocar O Bistial Lubellion por Invocação-Especial uma vez por turno desta forma. Você pode enviar este card da sua mão para o Cemitério; adicione 1 monstro Bistial do seu Deck à sua mão, exceto O Bistial Lubellion. Durante sua Fase Principal: você pode colocar 1 Magia/Armadilha Contínua Marcado do seu Deck no seu campo com a face para cima. Você só pode usar cada efeito de O Bistial Lubellion uma vez por turno.', 'https://img.mypcards.com/img/3/1874/yugioh_mp23_en160/yugioh_mp23_en160_en.jpg', 'R$140,00', 'Monstro ', '2500', '3000', 'Dragon,Effect', '8', '', '', '', ''),
(27, 'Preparação de Ritos', 'Adicione 1 Monstro de Ritual de Nível 7 ou menos do seu Deck à sua mão e, depois, você pode adicionar 1 Magia de Ritual do seu Cemitério à sua mão.', 'https://img.mypcards.com/img/3/2128/yugioh_ra02-en056/yugioh_ra02-en056_en-1716572419.jpeg', 'R$5,00', 'Magia', '0', '0', '', '0', '', '', '', ''),
(28, 'Controlador de Inimigos', 'Ative 1 desses efeitos. ● Escolha 1 monstro com a face para cima que seu oponente controla; mude a posição de batalha do alvo. ● Ofereça 1 monstro como Tributo e, depois, escolha 1 monstro com a face para cima que seu oponente controla; tome o controle do alvo até a Fase Final.', 'https://img.mypcards.com/img/3/2128/yugioh_ra02-en051/yugioh_ra02-en051_en-1716572130.jpeg', 'R$7,00', 'Magia', '0', '0', '', '0', '', '', '', ''),
(29, 'Sol e Luna', 'Escolha 1 monstro que você controla e 1 monstro que seu oponente controla; aplique o seguinte efeito em cada monstro, dependendo da sua posição de batalha. ● Face para cima: Coloque-o com a face para baixo em Posição de Defesa. ● Face para baixo: Coloque-o com a face para cima em Posição de Defesa. Você só pode ativar 1 Sol e Luna por turno.', 'https://img.mypcards.com/img/3/2128/yugioh_ra02-en068/yugioh_ra02-en068_en-1716573781.jpeg', 'R$5,00', 'Magia', '0', '0', '', '0', '', '', '', ''),
(30, 'Polimerização', 'Invoque por Invocação-Fusão 1 Monstro de Fusão do seu Deck Adicional, usando monstros da sua mão ou do campo como Matéria de Fusão.', 'https://img.mypcards.com/img/3/2128/yugioh_ra02-en047/yugioh_ra02-en047_en-1716571920.jpeg', 'R$10,00', 'Magia', '', '', '', '', '', '', '', ''),
(31, 'Enterro Tolo', 'Envie 1 monstro do seu Deck para o Cemitério.', 'https://img.mypcards.com/img/3/2128/yugioh_ra02-en049/yugioh_ra02-en049_en-1716572032.jpeg', 'R$8,00', 'Magia', '', '', '', '', '', '', '', ''),
(32, 'Schuberta, a Maestra Melodiosa', '2 monstros Melodiosa Durante o turno de qualquer duelista: você pode escolher até 3 cards em quaisquer Cemitérios; bana-os e, se isso acontecer, este card ganha 200 de ATK para cada um. Este efeito só pode ser usado uma vez enquanto este card estiver com a face para cima no campo.', 'https://img.mypcards.com/img/3/748/yugioh_sp17_053/yugioh_sp17_053_en.jpg', 'R$30,00', 'Monstro', '2400', '2000', 'Fairy,Fusion,Effect', '6', '', '', '', ''),
(33, 'Aleister, Aquele que Invoca', '(Efeito Rápido): você pode enviar este card da sua mão para o Cemitério e, depois, escolha 1 Monstro de Fusão que você controla; ele ganha 1000 de ATK/DEF até o final deste turno. Se este card for Invocado por Invocação-Normal ou virado com a face para cima: você pode adicionar 1 Invocação do seu Deck à sua mão.', 'https://img.mypcards.com/img/3/1349/yugioh_mago_en016/yugioh_mago_en016_en.jpg', 'R$30,00', 'Monstro', '1000', '1800', 'Spellcaster,Effect', '4', '', '', '', ''),
(34, 'Gandora-G, o Dragão da Destruição', 'Ganha 300 de ATK para cada card banido. Você só pode usar cada um dos seguintes efeitos de Gandora-G, o Dragão da Destruição uma vez por turno. Se você controlar Sarcófago Brilhante: você pode Invocar este card por Invocação-Especial da sua mão. Você pode pagar metade dos seus PV; destrua tantos outros cards no campo quanto possível e, se isso acontecer, bana-os e, depois, Invoque por Invocação-Especial do seu Deck 1 monstro de Nível 7 ou menos que mencione Sarcófago Brilhante e aumente o Nível dele pelo número de cards destruídos por este efeito.', 'https://img.mypcards.com/img/3/2118/yugioh_lede_en001/yugioh_lede_en001_en.jpg', 'R$70,00', 'Monstro', '0', '0', 'Dragon,Effect', '8', '', '', '', ''),
(35, 'Soberano Lucano Ragnaraika', '2+ monstros Inseto, Planta e/ou Réptil Se um ou mais monstros forem Invocados por Invocação-Especial do Deck e/ou Deck Adicional do seu oponente (exceto durante a Etapa de Dano): você pode destruir 2 monstros no campo. Se este card estiver no seu Cemitério: você pode escolher 1 monstro Inseto, Planta ou Réptil que você controla; coloque-o no fundo do Deck e, se isso acontecer, Invoque este card por Invocação-Especial e, além disso, você não pode Invocar por Invocação-Especial pelo resto deste turno, exceto monstros Inseto, Planta ou Réptil. Você só pode usar cada efeito de Soberano Lucano Ragnaraika uma vez por turno.', 'https://img.mypcards.com/img/3/2118/yugioh_lede_en050/yugioh_lede_en050_en.jpg', 'R$50,00', 'Monstro ', '3300', '', 'Insect,Link,Effect', '', '', '', '', '');

ALTER TABLE `cartas`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `cartas`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=36;
COMMIT;